create table public.system_logs (
  id bigint generated by default as identity not null,
  request text null,
  created_at timestamp with time zone not null default now(),
  api_request integer null,
  uploaded_pdf integer null,
  constraint api_logs_pkey primary key (id),
  constraint system_logs_request_fkey foreign KEY (request) references auth (email) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;