"use client";
import styles from "./css/styles.module.css";
import { Area, AreaChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useEffect, useState } from "react";
import apiLink from "@/config/conf/json_config/fetch_url.json";
import { Fetch_to } from "@/utilities";

type Range = "week" | "year";
type Point = { name: string; value: number };
type Data = { metrics: { registeredAccounts: number; activeAccounts: number; documents: number; uploadedDocuments: number; apiUsage: number; businessAccounts: number; sales: number; pendingSales: number; completedPayments: number; pendingPayments: number }; charts: Record<string, Record<Range, Point[]>>; breakdowns: { departments: Point[]; roles: Point[]; paymentStatus: Point[] }; topUsers: { email: string; usage: number }[]; insights: string[] };
const peso = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" });
const colors = ["#2563eb", "#8b5cf6", "#16a34a", "#f59e0b", "#ef4444", "#06b6d4"];

function Trend({ title, data, sales = false }: { title: string; data: Point[]; sales?: boolean }) {
    const hasData = data.some((point) => point.value > 0);
    return <section className={styles.graph}><div className={styles.chartHeader}><h2>{title}</h2><span className={hasData ? styles.trendUp : styles.trendDown}>{hasData ? "Live data" : "No activity yet"}</span></div><div className={styles.chartShell}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 10, right: 12, left: -12 }}><defs><linearGradient id={`fill-${title}`} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity={.4}/><stop offset="100%" stopColor="#2563eb" stopOpacity={.02}/></linearGradient></defs><CartesianGrid stroke="rgba(16,56,108,.16)" strokeDasharray="4 4" vertical={false}/><XAxis dataKey="name" tick={{ fill: "#4c5f85", fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis tick={{ fill: "#4c5f85", fontSize: 11 }} axisLine={false} tickLine={false} allowDecimals={false}/><Tooltip formatter={(value) => [sales ? peso.format(Number(value)) : Number(value).toLocaleString(), title]} contentStyle={{ borderRadius: 10, border: "1px solid #dbe4f0" }}/><Area type="monotone" dataKey="value" stroke="#2563eb" strokeWidth={2.5} fill={`url(#fill-${title})`}/></AreaChart></ResponsiveContainer></div></section>;
}
function Donut({ title, data }: { title: string; data: Point[] }) {
    const values = data.filter((item) => item.value > 0);
    return <section className={styles.pieCard}><h3>{title}</h3>{values.length ? <div className={styles.pieShell}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={values} dataKey="value" nameKey="name" innerRadius={55} outerRadius={86} paddingAngle={3}>{values.map((item, index) => <Cell key={item.name} fill={colors[index % colors.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></div> : <p className={styles.emptyState}>No data yet</p>}</section>;
}

export default function Dashboard({ email }: { email: string }) {
    const [range, setRange] = useState<Range>("week"); const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
    const load = async (background = false) => { if (!email) return; if (!background) setLoading(true); setError(""); const response = await Fetch_to(apiLink.admin.dashboard, { email }); if (response.success && response.data?.data) setData(response.data.data as Data); else setError(response.message || "Unable to load dashboard analytics."); if (!background) setLoading(false); };
    useEffect(() => {
        load();
        const interval = window.setInterval(() => load(true), 5000);
        return () => window.clearInterval(interval);
    }, [email]);
    const metrics = data?.metrics;
    const cards = metrics ? [["Collected sales", peso.format(metrics.sales), `${metrics.completedPayments} approved payments`], ["Pending sales", peso.format(metrics.pendingSales), `${metrics.pendingPayments} awaiting review`], ["Registered accounts", metrics.registeredAccounts.toLocaleString(), `${metrics.activeAccounts} active`], ["Business accounts", metrics.businessAccounts.toLocaleString(), "Current customers"], ["Documents", metrics.documents.toLocaleString(), `${metrics.uploadedDocuments} uploads logged`], ["AI requests", metrics.apiUsage.toLocaleString(), "Total recorded usage"]] : [];
    return <section className={styles.container}><header className={styles.header_cons}><span><svg width="24" height="24" viewBox="0 0 24 24" fill="none"><rect x="3" y="3" width="7" height="7" stroke="currentColor" strokeWidth="2"/><rect x="14" y="3" width="7" height="7" stroke="currentColor" strokeWidth="2"/><rect x="3" y="14" width="7" height="7" stroke="currentColor" strokeWidth="2"/><rect x="14" y="14" width="7" height="7" stroke="currentColor" strokeWidth="2"/></svg><h1>Dashboard</h1></span></header>{error ? <div className={styles.errorState}>{error}<button onClick={() => load()}>Try again</button></div> : <><section className={styles.salesHero}><div><span>Sales overview</span><h2>{metrics ? peso.format(metrics.sales) : "—"}</h2><p>Collected revenue from approved payments. Amounts already include VAT.</p></div><div className={styles.insights}><strong>Operational insights</strong>{data?.insights.map((item) => <p key={item}>{item}</p>)}</div></section><section className={styles.info}>{loading ? Array.from({ length: 6 }).map((_, index) => <div className={styles.loadingCard} key={index}/>) : cards.map(([label, value, detail]) => <div key={label}><h3>{label}</h3><p>{value}</p><small>{detail}</small></div>)}</section>{data && <section className={styles.analytics_data}><div className={styles.graph_container}><div className={styles.chartControls}><h3 className={styles.reportTitle}>Growth & revenue</h3><select value={range} onChange={(event) => setRange(event.target.value as Range)}><option value="week">Last 7 days</option><option value="year">Last 12 months</option></select></div><Trend title="New accounts" data={data.charts.accounts[range]}/><Trend title="Documents added" data={data.charts.documents[range]}/><Trend title="Sales collected" data={data.charts.sales[range]} sales/></div><div className={styles.records}><h3 className={styles.reportTitle}>Audience & payments</h3><Donut title="Department breakdown" data={data.breakdowns.departments}/><Donut title="Account roles" data={data.breakdowns.roles}/><Donut title="Payment pipeline" data={data.breakdowns.paymentStatus}/><h3 className={styles.reportTitle}>Top users by AI usage</h3><div className={styles.tableScroll}><table className={styles.rankings}><thead><tr><th>Rank</th><th>Email</th><th>AI requests</th></tr></thead><tbody>{data.topUsers.length ? data.topUsers.map((user, index) => <tr key={user.email}><td>#{index + 1}</td><td>{user.email}</td><td>{user.usage.toLocaleString()}</td></tr>) : <tr><td colSpan={3}>No usage recorded yet</td></tr>}</tbody></table></div></div></section>}</>}</section>;
}
